export const emailData = [
  {
    id: 1,
    senderEmail: "anil.m@zelarsoft.com",
    senderName: "anil",
    description: "test data",
    createdDate: "01-06-2023 16:30 hrs",
    modifiedDate: "02-06-2023 16:30 hrs",
    subject: "test mail",
  },
  {
    id: 2,
    senderEmail: "raja@zelarsoft.com",
    senderName: "rajja",
    description: "test data by raja",
    createdDate: "01-06-2023 16:30 hrs",
    modifiedDate: "02-06-2023 16:30 hrs",
    subject: "test mail from raja",
  },

  {
    id: 3,
    senderEmail: "fayaz@zelarsoft.com",
    senderName: "fayaz",
    description: "I wish a very Happy New Year prosperous and joyfilled",
    createdDate: "01-06-2023 16:30 hrs",
    modifiedDate: "02-06-2023 16:30 hrs",
    subject: "Happy New Year",
  },
  {
    id:4 ,
    senderEmail: "sony@zelarsoft.com",
    senderName: "Sony",
    description: "The UFRS is drafted with the follwing req, please go through it.",
    createdDate: "01-06-2023 16:30 hrs",
    modifiedDate: "02-06-2023 16:30 hrs",
    subject: "UFRS",
  },
  {
    id: 5,
    senderEmail: "Harish@zelarsoft.com",
    senderName: "Harish",
    description: "The given docuemt is updated as per your requirement, please find it.",
    createdDate: "01-06-2023 16:30 hrs",
    modifiedDate: "02-06-2023 16:30 hrs",
    subject: "documemt review",
  },
  {
    id: 6,
    senderEmail: "chitti@zelarsoft.com",
    senderName: "jhansi",
    description: "i request you in regards with the subject please grant me a leave  ",
    createdDate: "01-06-2023 16:30 hrs",
    modifiedDate: "02-06-2023 16:30 hrs",
    subject: "leave",
  },
];

export const testData = [
  {
    id: 1,
    name: "Arman",
    title: "Suite 68",
    message: "Apt 139",
    time: "9:59 AM",
    emailFrom: "Mr",
  },
  {
    id: 2,
    name: "Cthrine",
    title: "Room 1890",
    message: "PO Box 39051",
    time: "6:42 AM",
    emailFrom: "Honorable",
  },
  {
    id: 3,
    name: "Dallas",
    title: "Suite 93",
    message: "Suite 36",
    time: "10:40 AM",
    emailFrom: "Mrs",
  },
  {
    id: 4,
    name: "Merline",
    title: "Room 543",
    message: "Suite 13",
    time: "8:43 AM",
    emailFrom: "Mrs",
  },
  {
    id: 5,
    name: "Lucia",
    title: "Suite 36",
    message: "Apt 1577",
    time: "6:02 AM",
    emailFrom: "Dr",
  },
  {
    id: 6,
    name: "Quinn",
    title: "16th Floor",
    message: "PO Box 56560",
    time: "5:21 PM",
    emailFrom: "Ms",
  },
  {
    id: 7,
    name: "Lu",
    title: "PO Box 53180",
    message: "Suite 95",
    time: "5:24 PM",
    emailFrom: "Mrs",
  },
  {
    id: 8,
    name: "Hube",
    title: "Suite 65",
    message: "Apt 1123",
    time: "4:14 AM",
    emailFrom: "Rev",
  },
  {
    id: 9,
    name: "Toby",
    title: "Room 1266",
    message: "Suite 1",
    time: "12:56 PM",
    emailFrom: "Mrs",
  },
  {
    id: 10,
    name: "Leia",
    title: "10th Floor",
    message: "Suite 53",
    time: "8:18 AM",
    emailFrom: "Mr",
  },
  {
    id: 11,
    name: "Wendi",
    title: "Suite 94",
    message: "3rd Floor",
    time: "11:06 PM",
    emailFrom: "Dr",
  },
  {
    id: 12,
    name: "Chev",
    title: "PO Box 14035",
    message: "3rd Floor",
    time: "6:13 AM",
    emailFrom: "Dr",
  },
  {
    id: 13,
    name: "Toddy",
    title: "Suite 11",
    message: "Apt 648",
    time: "2:09 AM",
    emailFrom: "Rev",
  },
  {
    id: 14,
    name: "Putnem",
    title: "PO Box 93261",
    message: "Apt 1639",
    time: "9:41 PM",
    emailFrom: "Mr",
  },
  {
    id: 15,
    name: "Judon",
    title: "Apt 1705",
    message: "Suite 65",
    time: "6:32 AM",
    emailFrom: "Mr",
  },
  {
    id: 16,
    name: "Ina",
    title: "PO Box 55919",
    message: "Suite 49",
    time: "4:49 PM",
    emailFrom: "Ms",
  },
  {
    id: 17,
    name: "Dene",
    title: "PO Box 20073",
    message: "Suite 47",
    time: "3:15 AM",
    emailFrom: "Ms",
  },
  {
    id: 18,
    name: "Gunther",
    title: "Suite 89",
    message: "Room 363",
    time: "1:21 PM",
    emailFrom: "Dr",
  },
  {
    id: 19,
    name: "Tobey",
    title: "Suite 77",
    message: "Apt 1666",
    time: "2:46 PM",
    emailFrom: "Ms",
  },
  {
    id: 20,
    name: "Shaine",
    title: "4th Floor",
    message: "Suite 38",
    time: "10:27 PM",
    emailFrom: "Mr",
  },
  {
    id: 21,
    name: "Shaine",
    title: "Room 568",
    message: "PO Box 81023",
    time: "9:26 PM",
    emailFrom: "Dr",
  },
  {
    id: 22,
    name: "Max",
    title: "PO Box 51090",
    message: "Suite 46",
    time: "8:51 AM",
    emailFrom: "Mrs",
  },
  {
    id: 23,
    name: "Ursulina",
    title: "8th Floor",
    message: "Apt 758",
    time: "5:31 PM",
    emailFrom: "Dr",
  },
  {
    id: 24,
    name: "Orv",
    title: "Apt 1921",
    message: "PO Box 95233",
    time: "4:42 AM",
    emailFrom: "Rev",
  },
  {
    id: 25,
    name: "Sumner",
    title: "Suite 3",
    message: "Room 34",
    time: "9:18 AM",
    emailFrom: "Honorable",
  },
  {
    id: 26,
    name: "Glenda",
    title: "8th Floor",
    message: "Room 1237",
    time: "4:59 AM",
    emailFrom: "Mrs",
  },
  {
    id: 27,
    name: "Marcelia",
    title: "Room 1281",
    message: "PO Box 64420",
    time: "1:13 AM",
    emailFrom: "Honorable",
  },
  {
    id: 28,
    name: "Pier",
    title: "7th Floor",
    message: "Suite 85",
    time: "4:27 AM",
    emailFrom: "Honorable",
  },
  {
    id: 29,
    name: "Davina",
    title: "13th Floor",
    message: "3rd Floor",
    time: "9:47 AM",
    emailFrom: "Mrs",
  },
  {
    id: 30,
    name: "Jacky",
    title: "Apt 1499",
    message: "PO Box 84981",
    time: "11:10 AM",
    emailFrom: "Honorable",
  },
  {
    id: 31,
    name: "Hubie",
    title: "Room 1122",
    message: "Suite 93",
    time: "11:01 PM",
    emailFrom: "Honorable",
  },
  {
    id: 32,
    name: "Ganny",
    title: "Apt 149",
    message: "Room 1513",
    time: "6:21 AM",
    emailFrom: "Dr",
  },
  {
    id: 33,
    name: "Aldric",
    title: "Suite 4",
    message: "Apt 1077",
    time: "4:29 AM",
    emailFrom: "Honorable",
  },
  {
    id: 34,
    name: "Early",
    title: "8th Floor",
    message: "Suite 100",
    time: "6:36 AM",
    emailFrom: "Rev",
  },
  {
    id: 35,
    name: "Willy",
    title: "12th Floor",
    message: "Suite 21",
    time: "4:18 PM",
    emailFrom: "Honorable",
  },
  {
    id: 36,
    name: "Henrik",
    title: "17th Floor",
    message: "Suite 44",
    time: "1:19 PM",
    emailFrom: "Ms",
  },
  {
    id: 37,
    name: "Hester",
    title: "PO Box 12666",
    message: "Suite 33",
    time: "3:54 AM",
    emailFrom: "Mr",
  },
  {
    id: 38,
    name: "Roberta",
    title: "PO Box 4519",
    message: "Suite 58",
    time: "4:22 AM",
    emailFrom: "Mrs",
  },
  {
    id: 39,
    name: "Sheelagh",
    title: "12th Floor",
    message: "Apt 1641",
    time: "3:08 AM",
    emailFrom: "Mrs",
  },
  {
    id: 40,
    name: "Jermain",
    title: "Suite 45",
    message: "PO Box 33256",
    time: "2:16 AM",
    emailFrom: "Honorable",
  },
  {
    id: 41,
    name: "Gisella",
    title: "Room 603",
    message: "2nd Floor",
    time: "8:53 PM",
    emailFrom: "Rev",
  },
  {
    id: 42,
    name: "Corabella",
    title: "Suite 37",
    message: "3rd Floor",
    time: "12:29 PM",
    emailFrom: "Dr",
  },
  {
    id: 43,
    name: "Jewel",
    title: "Apt 53",
    message: "Suite 49",
    time: "1:03 AM",
    emailFrom: "Rev",
  },
  {
    id: 44,
    name: "Dinny",
    title: "Room 1240",
    message: "Room 899",
    time: "2:47 AM",
    emailFrom: "Honorable",
  },
  {
    id: 45,
    name: "Lura",
    title: "PO Box 98473",
    message: "Room 1789",
    time: "10:28 AM",
    emailFrom: "Dr",
  },
  {
    id: 46,
    name: "Jyoti",
    title: "PO Box 34920",
    message: "2nd Floor",
    time: "10:13 AM",
    emailFrom: "Mr",
  },
  {
    id: 47,
    name: "Doloritas",
    title: "7th Floor",
    message: "Room 1298",
    time: "8:28 AM",
    emailFrom: "Mrs",
  },
  {
    id: 48,
    name: "Inez",
    title: "12th Floor",
    message: "Room 1931",
    time: "3:12 PM",
    emailFrom: "Dr",
  },
  {
    id: 49,
    name: "Harriett",
    title: "Room 1761",
    message: "12th Floor",
    time: "4:06 AM",
    emailFrom: "Honorable",
  },
  {
    id: 50,
    name: "Madelin",
    title: "Apt 1916",
    message: "10th Floor",
    time: "2:27 AM",
    emailFrom: "Dr",
  },
  {
    id: 51,
    name: "Rodie",
    title: "Room 1333",
    message: "Apt 318",
    time: "3:19 AM",
    emailFrom: "Rev",
  },
  {
    id: 52,
    name: "Faith",
    title: "Apt 738",
    message: "PO Box 90264",
    time: "1:13 AM",
    emailFrom: "Ms",
  },
  {
    id: 53,
    name: "Ringo",
    title: "PO Box 18974",
    message: "8th Floor",
    time: "3:19 AM",
    emailFrom: "Rev",
  },
  {
    id: 54,
    name: "Napoleon",
    title: "Apt 306",
    message: "Suite 29",
    time: "7:43 AM",
    emailFrom: "Ms",
  },
  {
    id: 55,
    name: "Manda",
    title: "Room 1819",
    message: "Apt 1557",
    time: "11:09 PM",
    emailFrom: "Honorable",
  },
  {
    id: 56,
    name: "Demetris",
    title: "Room 1902",
    message: "PO Box 3810",
    time: "7:37 PM",
    emailFrom: "Rev",
  },
  {
    id: 57,
    name: "Devlen",
    title: "PO Box 62398",
    message: "Suite 56",
    time: "7:37 PM",
    emailFrom: "Mr",
  },
  {
    id: 58,
    name: "Camey",
    title: "Apt 1934",
    message: "Suite 51",
    time: "6:04 AM",
    emailFrom: "Dr",
  },
  {
    id: 59,
    name: "Weber",
    title: "Room 305",
    message: "Apt 747",
    time: "5:31 AM",
    emailFrom: "Mrs",
  },
  {
    id: 60,
    name: "Craggie",
    title: "Apt 743",
    message: "PO Box 29808",
    time: "5:15 AM",
    emailFrom: "Dr",
  },
  {
    id: 61,
    name: "Ellerey",
    title: "14th Floor",
    message: "6th Floor",
    time: "5:57 PM",
    emailFrom: "Ms",
  },
  {
    id: 62,
    name: "Neile",
    title: "11th Floor",
    message: "19th Floor",
    time: "12:55 PM",
    emailFrom: "Honorable",
  },
  {
    id: 63,
    name: "Ravid",
    title: "5th Floor",
    message: "PO Box 15426",
    time: "9:56 PM",
    emailFrom: "Mrs",
  },
  {
    id: 64,
    name: "Bradford",
    title: "PO Box 84575",
    message: "Suite 86",
    time: "12:57 PM",
    emailFrom: "Honorable",
  },
  {
    id: 65,
    name: "Jessalyn",
    title: "Apt 770",
    message: "Suite 84",
    time: "6:58 PM",
    emailFrom: "Rev",
  },
  {
    id: 66,
    name: "Deane",
    title: "13th Floor",
    message: "Suite 74",
    time: "7:46 AM",
    emailFrom: "Honorable",
  },
  {
    id: 67,
    name: "Aluino",
    title: "Suite 12",
    message: "Suite 39",
    time: "2:28 PM",
    emailFrom: "Mrs",
  },
  {
    id: 68,
    name: "Alysa",
    title: "Suite 80",
    message: "PO Box 4838",
    time: "12:49 PM",
    emailFrom: "Rev",
  },
  {
    id: 69,
    name: "Jessika",
    title: "Apt 1821",
    message: "Apt 1456",
    time: "10:09 AM",
    emailFrom: "Ms",
  },
  {
    id: 70,
    name: "Maxwell",
    title: "Room 1277",
    message: "Apt 719",
    time: "10:59 PM",
    emailFrom: "Mr",
  },
  {
    id: 71,
    name: "Eldredge",
    title: "3rd Floor",
    message: "PO Box 71699",
    time: "4:58 AM",
    emailFrom: "Mr",
  },
  {
    id: 72,
    name: "Fedora",
    title: "Room 851",
    message: "7th Floor",
    time: "8:53 AM",
    emailFrom: "Ms",
  },
  {
    id: 73,
    name: "Isaak",
    title: "Suite 46",
    message: "Apt 1347",
    time: "2:08 AM",
    emailFrom: "Dr",
  },
  {
    id: 74,
    name: "Daveen",
    title: "Suite 45",
    message: "Room 233",
    time: "8:18 PM",
    emailFrom: "Dr",
  },
  {
    id: 75,
    name: "Arvy",
    title: "17th Floor",
    message: "17th Floor",
    time: "11:35 AM",
    emailFrom: "Mrs",
  },
  {
    id: 76,
    name: "Mavis",
    title: "Suite 50",
    message: "Room 774",
    time: "8:03 PM",
    emailFrom: "Ms",
  },
  {
    id: 77,
    name: "Kiersten",
    title: "PO Box 40755",
    message: "Room 1872",
    time: "10:24 AM",
    emailFrom: "Mrs",
  },
  {
    id: 78,
    name: "Adelina",
    title: "PO Box 59086",
    message: "Suite 76",
    time: "5:13 PM",
    emailFrom: "Rev",
  },
  {
    id: 79,
    name: "Corabelle",
    title: "PO Box 32219",
    message: "PO Box 25371",
    time: "11:07 PM",
    emailFrom: "Honorable",
  },
  {
    id: 80,
    name: "Averil",
    title: "Suite 24",
    message: "Apt 91",
    time: "10:11 AM",
    emailFrom: "Rev",
  },
  {
    id: 81,
    name: "Jereme",
    title: "Room 1810",
    message: "Apt 1592",
    time: "1:38 AM",
    emailFrom: "Ms",
  },
  {
    id: 82,
    name: "Shadow",
    title: "Apt 328",
    message: "Apt 1577",
    time: "3:06 PM",
    emailFrom: "Mr",
  },
  {
    id: 83,
    name: "Leticia",
    title: "Apt 223",
    message: "Suite 49",
    time: "1:54 PM",
    emailFrom: "Honorable",
  },
  {
    id: 84,
    name: "Brittani",
    title: "Room 1717",
    message: "5th Floor",
    time: "5:18 AM",
    emailFrom: "Dr",
  },
  {
    id: 85,
    name: "Cherice",
    title: "PO Box 60961",
    message: "Room 274",
    time: "2:49 PM",
    emailFrom: "Rev",
  },
  {
    id: 86,
    name: "Mina",
    title: "Suite 1",
    message: "PO Box 29469",
    time: "6:22 PM",
    emailFrom: "Honorable",
  },
  {
    id: 87,
    name: "Paul",
    title: "Apt 1416",
    message: "Apt 638",
    time: "12:05 AM",
    emailFrom: "Honorable",
  },
  {
    id: 88,
    name: "Gar",
    title: "4th Floor",
    message: "Suite 21",
    time: "11:06 AM",
    emailFrom: "Dr",
  },
  {
    id: 89,
    name: "Kirbie",
    title: "Apt 74",
    message: "Apt 674",
    time: "4:22 AM",
    emailFrom: "Honorable",
  },
  {
    id: 90,
    name: "Anstice",
    title: "PO Box 26408",
    message: "Room 1210",
    time: "9:13 PM",
    emailFrom: "Mr",
  },
  {
    id: 91,
    name: "Consolata",
    title: "Apt 1482",
    message: "Room 1827",
    time: "7:55 AM",
    emailFrom: "Ms",
  },
  {
    id: 92,
    name: "Bud",
    title: "PO Box 66091",
    message: "PO Box 31459",
    time: "7:19 PM",
    emailFrom: "Ms",
  },
  {
    id: 93,
    name: "Darsie",
    title: "Suite 98",
    message: "PO Box 55076",
    time: "8:19 PM",
    emailFrom: "Ms",
  },
  {
    id: 94,
    name: "Kingsly",
    title: "Room 1840",
    message: "5th Floor",
    time: "10:56 PM",
    emailFrom: "Dr",
  },
  {
    id: 95,
    name: "Donal",
    title: "Suite 64",
    message: "PO Box 97296",
    time: "12:05 AM",
    emailFrom: "Ms",
  },
  {
    id: 96,
    name: "Ynes",
    title: "Apt 1495",
    message: "Room 13",
    time: "1:36 AM",
    emailFrom: "Dr",
  },
  {
    id: 97,
    name: "Derwin",
    title: "PO Box 3118",
    message: "PO Box 19294",
    time: "2:46 AM",
    emailFrom: "Mr",
  },
  {
    id: 98,
    name: "Delano",
    title: "Room 1830",
    message: "Apt 1960",
    time: "6:10 PM",
    emailFrom: "Rev",
  },
  {
    id: 99,
    name: "Lotti",
    title: "13th Floor",
    message: "Room 1528",
    time: "3:24 PM",
    emailFrom: "Mrs",
  },
  {
    id: 100,
    name: "Halley",
    title: "19th Floor",
    message: "Room 936",
    time: "9:40 AM",
    emailFrom: "Honorable",
  },
];
